version: '3.5'

services:
  mega_api:
    build: ./
    command: ./wait-for-postgres.sh db ./bin/main.exe
    ports:
      - 80:80
    depends_on:
      - db
    environment:
      - DB_PASSWORD=SUPERPASSWORD
    networks:
      localnet:
        ipv4_address: 10.10.10.2


  db:
    restart: always
    image: postgres:latest
    volumes:
    - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=SUPERPASSWORD
    expose:
      - "5432"
    ports:
      - 5432:5432
    networks:
      localnet:
        ipv4_address: 10.10.10.3

networks:
  localnet:
    driver: bridge
    ipam: 
      config:
        - subnet: 10.10.10.0/24
          gateway: 10.10.10.1