name: notifyapi
description: RESTful API server written in dart. Works with JWT and Postgres. Implemented for synchronization of clients in the Notify project
version: 1.0.0
homepage: https://github.com/meg4cyberc4t/notify-api

environment:
  sdk: '>=2.15.0-168.0.dev <3.0.0'

dev_dependencies:
  lints: ^1.0.0

dependencies: 
  shelf_router: ^1.1.2
  angel3_orm_postgres: ^3.1.0
  postgres: ^2.4.1+2
  dart_jsonwebtoken: ^2.4.0
  yaml: ^3.1.0
  dotenv: ^3.0.0
  uuid: ^3.0.5
