name: notifyapi
description: RESTful API server written in dart. Works with JWT and Postgres. Implemented for synchronization of clients in the Notify project
version: 1.0.0
homepage: https://github.com/meg4cyberc4t/notify-api

environment:
  sdk: '>=2.14.0-168.0.dev <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.19.3
  http: ^0.13.4


dependencies: 
  shelf_router: ^1.1.2
  postgres: ^2.4.1+2
  dart_jsonwebtoken: ^2.4.0
  yaml: ^3.1.0
  dotenv: ^3.0.0
